#!/bin/bash
# =============================================================================
# DayZ Mod List Exporter
# Version: 0.6
# Author: Engineer Alpho (with assistance from Claude/Anthropic)
# License: GPL-3.0
# Repository: https://github.com/EngineerAlpho/dayz-mod-scripts
# =============================================================================
#
# Exports currently installed mods to a format usable by batch_install_mods.sh
# Perfect for backing up your mod list or setting up a new server.
#
# =============================================================================

# Load configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [ -f "$SCRIPT_DIR/config.sh" ]; then
    source "$SCRIPT_DIR/config.sh"
else
    echo "Error: config.sh not found!"
    echo "Please ensure config.sh is in the same directory as this script"
    exit 1
fi

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}  Export Current Mod List v0.6${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""

# Check if mod mapping file exists
if [ ! -f "$MOD_MAPPING_FILE" ]; then
    echo -e "${RED}Error: No mod mapping file found at $MOD_MAPPING_FILE${NC}"
    echo -e "${YELLOW}You need to have mods installed via download_workshop_mod.sh first${NC}"
    exit 1
fi

# Get output filename
echo -e "${YELLOW}Enter output filename (or press Enter for 'my_mod_list.txt'):${NC}"
read -p "> " output_file

if [ -z "$output_file" ]; then
    output_file="my_mod_list.txt"
fi

# Ensure .txt extension
if [[ ! "$output_file" =~ \.txt$ ]]; then
    output_file="${output_file}.txt"
fi

echo ""
echo -e "${BLUE}Exporting mod list to: $output_file${NC}"
echo ""

# Create header
cat > "$output_file" << 'EOF'
# DayZ Server Mod List
# Format: ModName - https://steamcommunity.com/sharedfiles/filedetails/?id=WORKSHOP_ID
# Lines starting with # are ignored
# Generated by export_mod_list.sh

EOF

# Read mod mapping and export
mod_count=0
while IFS=: read -r workshop_id mod_name; do
    # Remove @ prefix for display
    display_name="${mod_name#@}"
    echo "${display_name} - https://steamcommunity.com/sharedfiles/filedetails/?id=${workshop_id}" >> "$output_file"
    mod_count=$((mod_count + 1))
done < "$MOD_MAPPING_FILE"

echo -e "${GREEN}✓ Exported $mod_count mod(s)${NC}"
echo ""
echo -e "${CYAN}Output file: ${YELLOW}$output_file${NC}"
echo ""
echo -e "${BLUE}You can now use this file with:${NC}"
echo -e "  ${YELLOW}./batch_install_mods.sh $output_file${NC}"
echo ""
echo -e "${CYAN}Tip: Edit the file to:${NC}"
echo -e "  - Remove mods you don't want"
echo -e "  - Add new mods"
echo -e "  - Change the order (top = loads first)"
echo ""
